[package]
name = "mplay"
version = "0.3.0"
description = "Music player"
publish = false
edition = "2024"

[dependencies]
symphonia = "0.5.4"
rodio = { version = "0.20.1", default-features = false, features = [
    "symphonia-flac",
] }
ratatui = "0.29.0" # my deps ;(
