[package]
name = "fy"
version = "0.2.0"
description = "Music player"
publish = false
edition = "2021"

[dependencies]
symphonia = "0.5.4"
rodio = { version = "0.19.0", default-features = false, features = [
    "symphonia-all",
] }
ratatui = "0.29.0" # my deps ;(
